services:
    postgres:
        image: postgres:14
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        container_name: postgres_coffee
        ports:
            - '5432:5432'
        volumes:
            - ./postgres_data:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PG_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PG_PASSWORD}
        container_name: pgadmin_coffee
        ports:
            - '5050:80'
